name = "emqx-auth-worker"
main = "src/index.js"
compatibility_date = "2024-06-01"

routes = [
    { pattern = "$EMQX_CUSTOM_DOMAIN", custom_domain = true }
]
workers_dev = false
preview_urls = false

[[kv_namespaces]]
binding = "USERS"
id = "$EMQX_KV_NAMESPACE_ID"

[assets]
directory = "./public"
binding = "ASSETS"
not_found_handling = "single-page-application"
run_worker_first = true

[observability]
enabled = true
head_sampling_rate = 1