name: Deploy Cloudflare Worker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      # Set these in your GitHub Actions secrets or variables
      EMQX_KV_NAMESPACE_ID: ${{ vars.EMQX_KV_NAMESPACE_ID }}
      EMQX_CUSTOM_DOMAIN: ${{ vars.EMQX_CUSTOM_DOMAIN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Install Wrangler
        run: npm install -g wrangler

      - name: Substitute variables in wrangler.toml
        run: |
          export EMQX_KV_NAMESPACE_ID="$EMQX_KV_NAMESPACE_ID"
          export EMQX_CUSTOM_DOMAIN="$EMQX_CUSTOM_DOMAIN"
          envsubst < wrangler.toml > wrangler.toml.tmp
          mv wrangler.toml.tmp wrangler.toml

      - name: Set API_KEY secret for Worker
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          EMQX_AUTH_API_KEY: ${{ secrets.EMQX_AUTH_API_KEY }}
          EMQX_KV_NAMESPACE_ID: ${{ vars.EMQX_KV_NAMESPACE_ID }}
          EMQX_CUSTOM_DOMAIN: ${{ vars.EMQX_CUSTOM_DOMAIN }}
        run: |
          echo "$EMQX_AUTH_API_KEY" | wrangler secret put API_KEY

      - name: Publish to Cloudflare Workers
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          EMQX_KV_NAMESPACE_ID: ${{ vars.EMQX_KV_NAMESPACE_ID }}
          EMQX_CUSTOM_DOMAIN: ${{ vars.EMQX_CUSTOM_DOMAIN }}
        run: |
          wrangler deploy --minify 